<?php
include_once 'setting.inc.php';
$_lang['simplemodal'] = 'simpleModal';
$_lang['simplemodal_menu_desc'] = 'Управление модальными окнами.';
$_lang['simplemodal_intro_msg'] = 'Вы можете выделять сразу несколько предметов при помощи Shift или Ctrl.';
$_lang['simplemodal_items'] = 'Модальные окна';
$_lang['simplemodal_item_resource'] = 'ID ресурса';
$_lang['simplemodal_item_user_grid'] = 'Пользователь';
$_lang['simplemodal_item_group'] = 'Группа';
$_lang['simplemodal_item_id'] = 'Id';
$_lang['simplemodal_item_name'] = 'Название';
$_lang['simplemodal_item_description'] = 'Описание';
$_lang['simplemodal_item_time_delay'] = 'Время задержки';
$_lang['simplemodal_item_coockie'] = 'Время до следующего показа окна';
$_lang['simplemodal_item_time_start'] = 'Время начала показов';
$_lang['simplemodal_item_time_stop'] = 'Время окончания показов';
$_lang['simplemodal_item_chunk'] = 'Чанк модального окна';
$_lang['simplemodal_item_user'] = 'Выберите пользователя';
$_lang['simplemodal_item_usergroup'] = 'Выберите группу ';
$_lang['simplemodal_item_resource'] = 'id ресурса.';
$_lang['simplemodal_item_active'] = 'Активно';
$_lang['simplemodal_combo_select'] = 'Выберите из списка.';
$_lang['simplemodal_item_create'] = 'Создать модальное окно';
$_lang['simplemodal_item_update'] = 'Изменить модальное окно';
$_lang['simplemodal_item_enable'] = 'Включить модальное окно';
$_lang['simplemodal_items_enable'] = 'Включить модальные окна';
$_lang['simplemodal_item_disable'] = 'Отключить модальное окно';
$_lang['simplemodal_items_disable'] = 'Отключить модальные окна';
$_lang['simplemodal_item_remove'] = 'Удалить модальное окно';
$_lang['simplemodal_items_remove'] = 'Удалить модальные окна';
$_lang['simplemodal_item_remove_confirm'] = 'Вы уверены, что хотите удалить это модальное окно?';
$_lang['simplemodal_items_remove_confirm'] = 'Вы уверены, что хотите удалить эти модальные окна?';
$_lang['simplemodal_item_active'] = 'Включено';
$_lang['simplemodal_item_err_name'] = 'Вы должны указать имя модального окна.';
$_lang['simplemodal_item_err_ae'] = 'Модальное окно с таким именем уже существует.';
$_lang['simplemodal_item_err_nf'] = 'Модальное окно не найдено.';
$_lang['simplemodal_item_err_ns'] = 'Модальное окно не указано.';
$_lang['simplemodal_item_err_remove'] = 'Ошибка при удалении модального окна.';
$_lang['simplemodal_item_err_save'] = 'Ошибка при сохранении модального окна.';
$_lang['simplemodal_grid_search'] = 'Поиск';
$_lang['simplemodal_grid_actions'] = 'Действия';

$_lang['simplemodal_recipient_type'] = 'Тип получателя';
$_lang['simplemodal_create_user'] = 'Пользователь';
$_lang['simplemodal_create_usergroup'] = 'Группа';
$_lang['simplemodal_create_all'] = 'Все';


$_lang['simplemodal_user_no_empty'] = 'Для пользователя есть окно.';
$_lang['simplemodal_group_no_empty'] = 'Для группы уже есть окно.';